export const tabs = [
  {
    code: 'oz',
    lang: 'O‘zbek tilida',
    title: 'Sarlavha',
    publisher: 'Nashriyot',
    description: 'Tavsif',
    body: 'Matn',
    question: 'Savol matni',
    answer: 'Javob matni',
    name: 'Ism shariflari',
    location: 'Manzillari',
    position: 'Ilmiy darajalari',
    major: 'Sohalari',
    author: 'Muallif',
    comment: 'Fikr-mulohaza',
    project: 'Nomi',
    country: 'Davlati',
    rank: 'Hazratning lavozimlari',
    doer: 'Ilmiy ishni qiluvchi shaxs',
    index: 2,
  },
  {
    code: 'uz',
    lang: 'Ўзбек тилидa',
    title: 'Сарлавҳа',
    publisher: 'Нашриёт',
    description: 'Тавсиф',
    body: 'Матн',
    question: 'Савол матни',
    answer: 'Жавоб матни',
    name: 'Исм шарифлари',
    location: 'Манзиллари',
    position: 'Илмий даражалари',
    major: 'Соҳалари',
    author: 'Муаллиф',
    comment: 'Фикр-мулоҳаза',
    project: 'Номи',
    country: 'Давлати',
    rank: 'Ҳазратнинг лавозимлари',
    doer: 'Илмий ишни қилувчи шахс',
    index: 4,
  },
  {
    code: 'eng',
    lang: 'In English',
    title: 'Title',
    publisher: 'Publishing',
    description: 'Description',
    body: 'Text',
    question: 'Question text',
    answer: 'Answer text',
    name: 'Full name',
    location: 'Address',
    position: 'Academic degree',
    major: 'Field',
    author: 'Author',
    comment: 'Feedback',
    project: 'Name',
    country: 'Country',
    rank: 'Position of sir',
    doer: 'A person who does scientific work',
    index: 1,
  },
  {
    code: 'ru',
    lang: 'На русском',
    title: 'Название',
    publisher: 'Издательский',
    description: 'Описание',
    body: 'Текст',
    question: 'Текст вопроса',
    answer: 'Текст ответа',
    name: 'Полное имя',
    location: 'Адрес',
    position: 'Ученая степень',
    major: 'Направление',
    author: 'Автор',
    comment: 'Обратная связь',
    project: 'Название',
    country: 'Страна',
    rank: 'Позиция мистера',
    doer: 'Человек, который занимается научной работой',
    index: 3,
  },
  {
    code: 'ar',
    lang: 'بالعربية',
    title: 'لقب',
    publisher: 'نشر',
    description: 'وصف',
    body: 'نص',
    question: 'نص السؤال',
    answer: 'نص الإجابة',
    name: 'الاسم الكامل',
    location: 'عنوان',
    position: 'درجة أكاديمية',
    major: 'اتجاه',
    author: 'مؤلف',
    comment: 'ردود الفعل',
    project: 'اسم',
    country: 'دولة',
    rank: 'مواقف الرب',
    doer: 'الشخص الذي يقوم بعمل علمي',
    index: 0,
  },
]
